name: syspharma
description: Gestión de farmacia con roles.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Arquitectura y Estado
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  
  # Navegación y UI
  go_router: ^13.0.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  
  # Utilidades
  shared_preferences: ^2.2.2
  
  # IDIOMA (Requerido por Flutter nuevo)
  intl: ^0.20.0
  
  # GRÁFICOS (Versión reciente compatible con intl 0.20)
  syncfusion_flutter_charts: ^31.2.18

  # CALENDARIO
  table_calendar: ^3.1.2
  
  # Auth

  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # HERRAMIENTA PARA GENERAR ICONOS
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# CONFIGURACIÓN DEL ICONO
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icono.png" # Asegúrate de que esta imagen exista
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff" # Fondo blanco para Android nuevos
  adaptive_icon_foreground: "assets/images/icono.png"