name: syspharma
description: Gestión de farmacia con roles.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Arquitectura y Estado
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  
  # Navegación y UI
  go_router: ^13.0.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  
  # Utilidades
  shared_preferences: ^2.2.2
  
  # IDIOMA (Requerido por Flutter nuevo)
  intl: ^0.20.0
  
  # GRÁFICOS (Versión reciente compatible con intl 0.20)
  syncfusion_flutter_charts: ^31.2.18

  # CALENDARIO
  table_calendar: ^3.1.2
  
  # Auth
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/